### ISSUE TITLE
No audio from nyan demos

### ISSUE THREAD

**Issue by zomgugoff** [shieladixon/RC2014-TMS9918A#2]
I'm not hearing anything from the nyan demos. Visuals work. I have a rc2014-ym2149 R6 card configured for MSX registers. I can play music with tune.com. I saw it mentioned on a video that you had modified it to work on something, although I don't know if that was the version that is on this repo.

**Comment by shieladixon** [comment]
Hi

The version that's in my repository is built to expect the AY on 'traditional' RC2014 ports, D8 asnd D0. This is how I use my RC2014s, with an Ed Brindley R5 card, which can be jumpered to those ports.

(I notice that the version of the demo in JBL's repository is configured for ports $68 and $60).

Since there has been more interest in MSX and Ed has released the R6 board this question has come up a couple of times. The R5 is capable of being jumpered to those traditional RC2014 ports, but not MSX ones, and the R6 is capable of being jumpered to MSX ports but not the traditional RC2014 ones. 

I've been intending to put port detection into my build of the demo. I think that Tune does some port detection and therefore will find your card.

In the mean time, I can only suggest (if you're feeling brave) rebuilding JBL's source and altering the port numbers to MSX ones (near the top of PT3.asm). 


Shiela

**Comment by zomgugoff** [comment]
I would like to brave the process. I am, however, having issues getting a binary built that will run unmodified, little-lone with the port settings changed. Any tips for the inexperienced on building from source?

**Comment by shieladixon** [comment]
This is often a problem. compilers have their own 'dialect'. 

I don't know what JBL uses, but I find that those examples compile unmodified with my favourite compiler, zasm.

**Comment by shieladixon** [comment]
> I would like to brave the process. I am, however, having issues getting a binary built that will run unmodified, little-lone with the port settings changed. Any tips for the inexperienced on building from source?

I've been meaning to add port detection anyway, so to save you the pain I've done that and uploaded new binaries to this repository - 4 variants, NYANSD.COM, NYANSDGB.COM, NYANSDCH.COM and  NYANSDUN.COM

The sound should work whether you have a card using ports D8/D0 or MSX ports A0/A1

**Comment by zomgugoff** [comment]
Thanks for doing that, and the tip ;)
